[project]
name = "typing-counter"
version = "0.2.0"
description = "A simple typing counter application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pynput>=1.7.7",
]

[project.scripts]
typing-counter = "typing_counter.app:main"
